apiVersion: v5      
kind: URCap
urcap:
  name: hello-port 
  vendor: universal-robots
  version: 1.0 
artifacts:
  containers:
  - image: myservice-image
    name: myservice-name
    ports:
    - name: http
      containerPort: 8080
    volumeMounts:
    - mountPath: /mount

    